### ISSUE TITLE
Error: Cannot find module 'commander'

### ISSUE THREAD

**Issue by HuiyingShen96** [xujiujiu/i18n-collect-cli#4]
Error: Cannot find module 'commander'
Require stack:
- /usr/local/lib/node_modules/i18n-collect-cli/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/i18n-collect-cli/index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/lib/node_modules/i18n-collect-cli/index.js' ]
}

当我使用以下命令时，出现了上述报错信息：
```
i18n-cli getlang src -f zh.json -i assets,icon-color-components,icon-components
```

**Comment by xujiujiu** [comment]
已更新到0.1.2版本，更新下对应的npm版本即可
